# Generated by Django 4.0.6 on 2022-07-28 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DayMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date and Time')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modification Date and Time')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_id', models.PositiveBigIntegerField()),
                ('food_name', models.CharField(max_length=100)),
                ('calories', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('carbohydrate', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('protein', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('fat', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('saturated_fat', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('polyunsaturated_fat', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('monounsaturated_fat', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('trans_fat', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('cholesterol', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('sodium', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('potassium', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('fiber', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('sugar', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('added_sugars', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('vitamin_d', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('vitamin_a', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('vitamin_c', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('calcium', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('iron', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('measurement_description', models.CharField(max_length=100)),
                ('number_of_units', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='FoodMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serving_amount', models.DecimalField(decimal_places=1, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('time', models.TimeField()),
                ('icon', models.CharField(choices=[('Apple', 'Apple'), ('Carrot', 'Carrot'), ('Egg', 'Egg'), ('Lemon', 'Lemon'), ('Bacon', 'Bacon'), ('Chicken', 'Chicken'), ('Cheese', 'Cheese'), ('Cookie', 'Cookie'), ('Fish', 'Fish'), ('Burger', 'Burger')], max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
