# Generated by Django 4.0.6 on 2022-07-21 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('calories', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('carbohydrate', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('protein', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('fat', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('saturated_fat', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('polyunsaturated_fat', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('monounsaturated_fat', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('trans_fat', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('cholesterol', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('sodium', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('potassium', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('fiber', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('sugar', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('added_sugars', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('vitamin_d', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('vitamin_a', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('vitamin_c', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('calcium', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('iron', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('horario', models.TimeField()),
                ('creator', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='creator')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DayFit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date and Time')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modification Date and Time')),
                ('creator', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='creator')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
