# Generated by Django 4.0.6 on 2022-08-03 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calorie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='food_id',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='foodmeal',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calorie.food'),
        ),
    ]
