# Generated by Django 4.0.6 on 2022-07-21 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calorie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date and Time')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modification Date and Time')),
                ('creator', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='creator')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FoodMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serving_unit', models.CharField(choices=[('G', 'Gramas'), ('KG', 'Kilos'), ('ML', 'Mililitros'), ('L', 'Litros')], max_length=5)),
                ('serving_amount', models.DecimalField(decimal_places=1, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='food',
            name='amount_g',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.DeleteModel(
            name='DayFit',
        ),
        migrations.AddField(
            model_name='foodmeal',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calorie.food'),
        ),
        migrations.AddField(
            model_name='daymeal',
            name='foods',
            field=models.ManyToManyField(to='calorie.foodmeal'),
        ),
        migrations.AddField(
            model_name='daymeal',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calorie.meal'),
        ),
    ]
