# Generated by Django 4.0.6 on 2022-08-03 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calorie', '0003_alter_nutritionaldaygoal_calories_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.PositiveIntegerField(default=0)),
                ('fat', models.PositiveIntegerField(default=0)),
                ('muscle', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('creator', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='creator')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BodyDayGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Creation Date and Time')),
                ('modified', models.DateField(auto_now=True, verbose_name='Modification Date and Time')),
                ('weight', models.PositiveIntegerField(default=0)),
                ('fat', models.PositiveIntegerField(default=0)),
                ('muscle', models.PositiveIntegerField(default=0)),
                ('creator', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='creator')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calorie.bodygoal')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
