# Generated by Django 4.0.6 on 2022-08-04 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calorie', '0004_bodygoal_bodydaygoal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bodydaygoal',
            old_name='fat',
            new_name='fat_body',
        ),
        migrations.RenameField(
            model_name='bodygoal',
            old_name='fat',
            new_name='fat_body',
        ),
    ]
