# Generated by Django 4.0.6 on 2022-07-29 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorie', '0004_alter_food_added_sugars_alter_food_calcium_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='food_id',
            field=models.CharField(max_length=250),
        ),
    ]
